// Custom Service Worker logic for MedGenie
// This will be merged with the one generated by next-pwa

import { openDB } from 'idb';

const DB_NAME = 'medgenie-db';
const STORE_SYNC_QUEUE = 'sync_queue';
const API_BASE = 'http://localhost:8000/api'; // Fallback to localhost if ENV not injected

self.addEventListener('sync', (event: any) => {
  if (event.tag === 'health-sync') {
    event.waitUntil(syncHealthData());
  }
});

async function syncHealthData() {
  console.log('[SW] Background Sync: Starting health-sync');
  
  try {
    const db = await openDB(DB_NAME, 2);
    const tx = db.transaction(STORE_SYNC_QUEUE, 'readonly');
    const queue = await tx.objectStore(STORE_SYNC_QUEUE).getAll();

    if (queue.length === 0) {
      console.log('[SW] Background Sync: Queue is empty');
      return;
    }

    for (const item of queue) {
      try {
        const response = await fetch(`${API_BASE}${item.store === 'vitals' ? '/patients/vitals/' : '/voice-log/'}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            // Note: Authorization header might be needed here. 
            // In a real PWA, you'd store the token in the DB or use a cookie.
          },
          body: JSON.stringify(item.data),
        });

        if (response.ok) {
          // Mark as synced in the main store and remove from queue
          const deleteTx = db.transaction([STORE_SYNC_QUEUE, item.store], 'readwrite');
          await deleteTx.objectStore(STORE_SYNC_QUEUE).delete(item.id);
          
          const mainStore = deleteTx.objectStore(item.store as any);
          const original = await mainStore.get(item.data.id);
          if (original) {
            original.synced = true;
            await mainStore.put(original);
          }
          await deleteTx.done;
          
          console.log(`[SW] Successfully synced ${item.store} record`);
          
          // Show a notification to the user
          (self as any).registration.showNotification('MedGenie Data Synced', {
            body: `Your offline ${item.store} data has been securely uploaded to your Digital Twin.`,
            icon: '/icons/icon-192x192.png',
          });
        }
      } catch (err) {
        console.error('[SW] Failed to sync item:', err);
      }
    }
  } catch (err) {
    console.error('[SW] Global sync error:', err);
  }
}

// Handle push notifications if any
self.addEventListener('push', (event: any) => {
  const data = event.data?.json() ?? {};
  const title = data.title || 'MedGenie Alert';
  const options = {
    body: data.body || 'New health insight detected.',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/badge.png',
  };
  event.waitUntil((self as any).registration.showNotification(title, options));
});
