# Generated by Django 5.2.12 on 2026-04-02 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwinState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_scores', models.JSONField(default=dict, help_text='{"cardiac": 0.3, "diabetes": 0.7}')),
                ('active_conditions', models.JSONField(default=list)),
                ('predicted_events', models.JSONField(default=list)),
                ('graph_snapshot', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(default='v0.1.0', max_length=50)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'digital_twin_state',
            },
        ),
        migrations.CreateModel(
            name='GoogleFitToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField()),
                ('scopes', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_fit_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'google_fit_tokens',
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_source', models.CharField(choices=[('google_fit', 'Google Fit'), ('health_connect', 'Health Connect'), ('manual', 'Manual Entry'), ('device', 'IoT Device')], default='manual', max_length=50)),
                ('metric_type', models.CharField(choices=[('heart_rate', 'Heart Rate'), ('spo2', 'Blood Oxygen (SpO2)'), ('bp_systolic', 'Blood Pressure (Systolic)'), ('bp_diastolic', 'Blood Pressure (Diastolic)'), ('steps', 'Steps'), ('sleep_duration', 'Sleep Duration'), ('sleep_quality', 'Sleep Quality'), ('body_temp', 'Body Temperature'), ('respiratory_rate', 'Respiratory Rate'), ('calories', 'Calories Burned'), ('weight', 'Weight'), ('glucose', 'Blood Glucose'), ('activity_minutes', 'Active Minutes')], max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vitals',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', '-recorded_at'], name='vitals_patient_e36bc1_idx'), models.Index(fields=['metric_type', '-recorded_at'], name='vitals_metric__eb5c8c_idx')],
            },
        ),
    ]
